#pragma once

#include <ouster/core/frame_set.h>
#include <ouster/core/lidar_frame.h>
#include <ouster/core/types.h>
#include <ouster/core/visibility.h>

#include <vector>

namespace ouster {
namespace sdk {
namespace mapping {

/// @brief Common configuration parameters for SlamEngine implementations.
struct OUSTER_API_CLASS SlamConfig {
   protected:
    SlamConfig() = default;

   public:
    double min_range = 0.0;    ///< Minimum range of sensor measurements to be
                               ///< considered (meters)
    double max_range = 150.0;  ///< Maximum range of sensor measurements to be
                               ///< considered (meters)
    double voxel_size = 0.0;   ///< Size of the voxel grid for downsampling
    int max_iterations = 500;  ///< Maximum number of ICP registration iterations
    core::Matrix4dR initial_pose = core::Matrix4dR::Identity();  ///< Initial pose of the sensor
    std::string deskew_method = "auto";                          ///< Deskewing method to be applied
};

/**
 * @brief Configuration class for the LIO-based SlamEngine.
 */
struct OUSTER_API_CLASS LIOSlamConfig : public SlamConfig {
    /// Default constructor for LIOSlamConfig.
    OUSTER_API_FUNCTION
    LIOSlamConfig() = default;
};

/**
 * @class SlamEngine
 * @brief SLAM engine for processing sensor data using specified backend.
 *
 * This class provides an interface for running SLAM (Simultaneous Localization
 * and Mapping) algorithms on lidar and other sensor data.
 *
 * @note Only the "lio" backend is supported at this time.
 *
 * @see LidarFrame
 * @see SlamConfig
 */
class OUSTER_API_CLASS SlamEngine {
   public:
    /**
     * @brief Constructs the SlamEngine, using a default config.
     *
     * @param[in] infos A vector of shared pointers to SensorInfo objects.
     * @param[in] config Configuration parameters. Defaults to LIOSlamConfig{}.
     * @return A unique pointer to the created SlamEngine instance.
     */
    OUSTER_API_FUNCTION
    static std::unique_ptr<SlamEngine> create(
        const std::vector<std::shared_ptr<ouster::sdk::core::SensorInfo>>& infos,
        const LIOSlamConfig& config = LIOSlamConfig{});

    /// Destructor for SlamEngine.
    OUSTER_API_FUNCTION
    virtual ~SlamEngine() = default;

    /**
     * @brief Let SlamEngine process LidarFrames to estimate the new state
     * (pose).
     *
     * This function processes a set of LidarFrames provided as vector of shared
     * pointers of LidarFrame, The engine returns these LidarFrames with their
     * per-column body_to_world transform corrected.
     *
     * @param[in,out] frame_set A vector of LidarFrame objects to
     * be processed.
     */
    OUSTER_API_FUNCTION
    virtual void update(ouster::sdk::core::FrameSet& frame_set) = 0;

    /**
     * @brief Retrieves the current point cloud from the SLAM engine.
     *
     * This method returns a point cloud representation as a `PointCloudXYZf`
     * object, which contains the latest set of 3D points generated by the SLAM
     * engine.
     *
     * @return A `PointCloudXYZf` object containing the current point cloud
     * data.
     */
    OUSTER_API_FUNCTION
    virtual ouster::sdk::core::PointCloudXYZf get_point_cloud() const = 0;

   protected:
    SlamEngine(const std::vector<std::shared_ptr<ouster::sdk::core::SensorInfo>>& infos)
        : infos_(infos) {}

    std::vector<std::shared_ptr<ouster::sdk::core::SensorInfo>> infos_;
};

}  // namespace mapping
}  // namespace sdk
}  // namespace ouster
