/**
 * Copyright (c) 2025, Ouster, Inc.
 * All rights reserved.
 *
 * @file
 * @brief ouster_pyclient
 *
 * Note: the type annotations in `client.pyi` need to be updated whenever this
 * file changes. See the mypy documentation for details.
 */

#include <nanobind/nanobind.h>
#include <nanobind/ndarray.h>
#include <nanobind/stl/pair.h>
#include <nanobind/stl/vector.h>
#include <pyerrors.h>
#include <warnings.h>

#include "common.h"
#include "eigen_dense.h"

void init_client_client(py::module_& module, py::module_& /*unused*/);
void init_client_data(py::module_& module, py::module_& /*unused*/);
void init_client_field(py::module_& module, py::module_& /*unused*/);
void init_client_object(py::module_& module, py::module_& /*unused*/);
void init_client_lidar_frame(py::module_& module, py::module_& /*unused*/);
void init_client_misc(py::module_& module, py::module_& /*unused*/);
void init_client_packet(py::module_& module, py::module_& /*unused*/);
void init_client_processing(py::module_& module, py::module_& /*unused*/);
void init_client_pose(py::module_& module, py::module_& /*unused*/);
void init_client_frame_ops(py::module_& module, py::module_& /*unused*/);
void init_client_frame_set_source(py::module_& module, py::module_& /*unused*/);
void init_client_zone_monitor(py::module_& module, py::module_& /*unused*/);

void init_client(py::module_& module, py::module_& main_module) {
    module.doc() = R"(
    Sensor client bindings generated by nanobind.

    This module is generated directly from the C++ code and not meant to be used
    directly.
    )";

    init_client_pose(module, main_module);
    init_client_object(module, main_module);
    init_client_field(module, main_module);
    init_client_lidar_frame(module, main_module);
    init_client_data(module, main_module);
    init_client_misc(module, main_module);
    init_client_packet(module, main_module);
    init_client_processing(module, main_module);
    init_client_frame_ops(module, main_module);
    init_client_zone_monitor(module, main_module);
    init_client_frame_set_source(module, main_module);
    init_client_client(module, main_module);
}
