/**
 * Copyright (c) 2025, Ouster, Inc.
 * All rights reserved.
 *
 * @file
 * @brief ouster_pyclient
 *
 * Note: the type annotations in `client.pyi` need to be updated whenever this
 * file changes. See the mypy documentation for details.
 */

#include <pybind11/eigen.h>
#include <pybind11/functional.h>
#include <pybind11/numpy.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/stl_bind.h>
#include <pyerrors.h>
#include <warnings.h>

namespace py = pybind11;

void init_client_client(py::module& module, py::module& /*unused*/);
void init_client_data(py::module& module, py::module& /*unused*/);
void init_client_field(py::module& module, py::module& /*unused*/);
void init_client_lidar_scan(py::module& module, py::module& /*unused*/);
void init_client_misc(py::module& module, py::module& /*unused*/);
void init_client_packet(py::module& module, py::module& /*unused*/);
void init_client_processing(py::module& module, py::module& /*unused*/);
void init_client_scan_source(py::module& module, py::module& /*unused*/);
void init_client_zone_monitor(py::module& module, py::module& /*unused*/);

void init_client(py::module& module, py::module& main_module) {
    module.doc() = R"(
    Sensor client bindings generated by pybind11.

    This module is generated directly from the C++ code and not meant to be used
    directly.
    )";
    py::class_<std::pair<int, int>>(module, "IntPair");
    init_client_field(module, main_module);
    init_client_lidar_scan(module, main_module);
    init_client_data(module, main_module);
    init_client_misc(module, main_module);
    init_client_packet(module, main_module);
    init_client_processing(module, main_module);
    init_client_zone_monitor(module, main_module);
    init_client_scan_source(module, main_module);
    init_client_client(module, main_module);
}
