
if ( NOT DEFINED CATKIN_GLOBAL_INCLUDE_DESTINATION)
  set(CATKIN_GLOBAL_INCLUDE_DESTINATION include )
endif() 

if ( NOT DEFINED CATKIN_GLOBAL_BIN_DESTINATION) 
  set(CATKIN_GLOBAL_BIN_DESTINATION bin )
endif()

if ( NOT DEFINED CATKIN_GLOBAL_BIN_DESTINATION) 
  set(CATKIN_GLOBAL_BIN_DESTINATION bin )
endif()

if ( NOT DEFINED CATKIN_GLOBAL_LIB_DESTINATION)
  set(CATKIN_GLOBAL_LIB_DESTINATION lib)
endif()

if (NOT DEFINED CATKIN_GLOBAL_LIBEXEC_DESTINATION )
  set(CATKIN_GLOBAL_LIBEXEC_DESTINATION lib)
endif()

if (NOT DEFINED CATKIN_GLOBAL_SHARE_DESTINATION)
  set(CATKIN_GLOBAL_SHARE_DESTINATION share )
endif()

if ( NOT DEFINED CATKIN_PACKAGE_LIB_DESTINATION )
  set(CATKIN_PACKAGE_LIB_DESTINATION lib)
endif()

if ( NOT DEFINED CATKIN_PACKAGE_BIN_DESTINATION )
  set(CATKIN_PACKAGE_BIN_DESTINATION lib/${PROJECT_NAME})
endif()

if (NOT DEFINED CATKIN_PACKAGE_INCLUDE_DESTINATION)
  set(CATKIN_PACKAGE_INCLUDE_DESTINATION include/${PROJECT_NAME} )
endif()

if (NOT DEFINED CATKIN_PACKAGE_SHARE_DESTINATION)
  set(CATKIN_PACKAGE_SHARE_DESTINATION share/${PROJECT_NAME} )
endif()
