from typing import Generic, TypeVar, Optional
from threading import Condition

_T = TypeVar("_T")

class LifoQueue(Generic[_T]):
    maxsize: int
    mutex: Condition

    def __init__(self, maxsize: int = 0) -> None: ...
    def qsize(self) -> int: ...
    def empty(self) -> bool: ...
    def full(self) -> bool: ...
    def put(self, item: _T, block: bool = True, timeout: Optional[float] = None) -> None: ...
    def put_nowait(self, item: _T) -> None: ...
    def get(self, block: bool = True, timeout: Optional[float] = None) -> _T: ...
    def get_nowait(self) -> _T: ...
    def task_done(self) -> None: ...
    def join(self) -> None: ...
