#pragma once

namespace ouster {
namespace sdk {
namespace core {

/// @cond DOXYGEN_SHOULD_SKIP_THIS
OUSTER_DEPRECATED_CONSTEXP(MODE_UNSPEC, LidarMode::UNSPECIFIED,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(MODE_512x10, LidarMode::_512x10,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(MODE_512x20, LidarMode::_512x20,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(MODE_1024x10, LidarMode::_1024x10,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(MODE_1024x20, LidarMode::_1024x20,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(MODE_2048x10, LidarMode::_2048x10,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(MODE_4096x5, LidarMode::_4096x5,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);

OUSTER_DEPRECATED_CONSTEXP(TIME_FROM_UNSPEC, TimestampMode::UNSPECIFIED,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(TIME_FROM_INTERNAL_OSC,
                           TimestampMode::TIME_FROM_INTERNAL_OSC,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(TIME_FROM_SYNC_PULSE_IN,
                           TimestampMode::TIME_FROM_SYNC_PULSE_IN,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(TIME_FROM_PTP_1588,
                           TimestampMode::TIME_FROM_PTP_1588,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);

OUSTER_DEPRECATED_CONSTEXP(OPERATING_UNSPEC, OperatingMode::UNSPECIFIED,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(OPERATING_NORMAL, OperatingMode::NORMAL,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(OPERATING_STANDBY, OperatingMode::STANDBY,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);

OUSTER_DEPRECATED_CONSTEXP(MULTIPURPOSE_OFF, MultipurposeIOMode::OFF,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(MULTIPURPOSE_INPUT_NMEA_UART,
                           MultipurposeIOMode::INPUT_NMEA_UART,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(MULTIPURPOSE_OUTPUT_FROM_INTERNAL_OSC,
                           MultipurposeIOMode::OUTPUT_FROM_INTERNAL_OSC,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(MULTIPURPOSE_OUTPUT_FROM_SYNC_PULSE_IN,
                           MultipurposeIOMode::OUTPUT_FROM_SYNC_PULSE_IN,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(MULTIPURPOSE_OUTPUT_FROM_PTP_1588,
                           MultipurposeIOMode::OUTPUT_FROM_PTP_1588,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(MULTIPURPOSE_OUTPUT_FROM_ENCODER_ANGLE,
                           MultipurposeIOMode::OUTPUT_FROM_ENCODER_ANGLE,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);

OUSTER_DEPRECATED_CONSTEXP(POLARITY_ACTIVE_LOW, Polarity::ACTIVE_LOW,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(POLARITY_ACTIVE_HIGH, Polarity::ACTIVE_HIGH,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
/// @endcond

/// @cond DOXYGEN_SHOULD_SKIP_THIS

OUSTER_DEPRECATED_CONSTEXP(PROFILE_LIDAR_UNKNOWN, UDPProfileLidar::UNKNOWN,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(PROFILE_LIDAR_LEGACY, UDPProfileLidar::LEGACY,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(PROFILE_RNG19_RFL8_SIG16_NIR16_DUAL,
                           UDPProfileLidar::RNG19_RFL8_SIG16_NIR16_DUAL,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(PROFILE_RNG19_RFL8_SIG16_NIR16,
                           UDPProfileLidar::RNG19_RFL8_SIG16_NIR16,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(PROFILE_RNG15_RFL8_NIR8,
                           UDPProfileLidar::RNG15_RFL8_NIR8,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(PROFILE_FIVE_WORD_PIXEL,
                           UDPProfileLidar::FIVE_WORD_PIXEL,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(PROFILE_FUSA_RNG15_RFL8_NIR8_DUAL,
                           UDPProfileLidar::FUSA_RNG15_RFL8_NIR8_DUAL,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(PROFILE_RNG15_RFL8_NIR8_DUAL,
                           UDPProfileLidar::RNG15_RFL8_NIR8_DUAL,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(PROFILE_RNG15_RFL8_NIR8_ZONE16,
                           UDPProfileLidar::RNG15_RFL8_NIR8_ZONE16,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(PROFILE_RNG19_RFL8_SIG16_NIR16_ZONE16,
                           UDPProfileLidar::RNG19_RFL8_SIG16_NIR16_ZONE16,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(PROFILE_LIDAR_OFF, UDPProfileLidar::OFF,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);

OUSTER_DEPRECATED_CONSTEXP(PROFILE_IMU_LEGACY, UDPProfileIMU::LEGACY,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(PROFILE_ACCEL32_GYRO32_NMEA,
                           UDPProfileIMU::ACCEL32_GYRO32_NMEA,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(PROFILE_IMU_OFF, UDPProfileIMU::OFF,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);

OUSTER_DEPRECATED_CONSTEXP(FSR_NORMAL, FullScaleRange::NORMAL,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(FSR_EXTENDED, FullScaleRange::EXTENDED,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);

OUSTER_DEPRECATED_CONSTEXP(ORDER_STRONGEST_TO_WEAKEST,
                           ReturnOrder::STRONGEST_TO_WEAKEST,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(ORDER_FARTHEST_TO_NEAREST,
                           ReturnOrder::FARTHEST_TO_NEAREST,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(ORDER_NEAREST_TO_FARTHEST,
                           ReturnOrder::NEAREST_TO_FARTHEST,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(ORDER_DEPRECATED_STRONGEST_RETURN_FIRST,
                           ReturnOrder::DEPRECATED_STRONGEST_RETURN_FIRST,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(ORDER_DEPRECATED_LAST_RETURN_FIRST,
                           ReturnOrder::DEPRECATED_LAST_RETURN_FIRST,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);

OUSTER_DEPRECATED_CONSTEXP(THERMAL_SHUTDOWN_NORMAL,
                           ThermalShutdownStatus::NORMAL,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(THERMAL_SHUTDOWN_IMMINENT,
                           ThermalShutdownStatus::IMMINENT,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);

OUSTER_DEPRECATED_CONSTEXP(SHOT_LIMITING_NORMAL, ShotLimitingStatus::NORMAL,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(SHOT_LIMITING_IMMINENT, ShotLimitingStatus::IMMINENT,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(SHOT_LIMITING_REDUCTION_0_10,
                           ShotLimitingStatus::REDUCTION_0_10,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(SHOT_LIMITING_REDUCTION_10_20,
                           ShotLimitingStatus::REDUCTION_10_20,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(SHOT_LIMITING_REDUCTION_20_30,
                           ShotLimitingStatus::REDUCTION_20_30,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(SHOT_LIMITING_REDUCTION_30_40,
                           ShotLimitingStatus::REDUCTION_30_40,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(SHOT_LIMITING_REDUCTION_40_50,
                           ShotLimitingStatus::REDUCTION_40_50,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(SHOT_LIMITING_REDUCTION_50_60,
                           ShotLimitingStatus::REDUCTION_50_60,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(SHOT_LIMITING_REDUCTION_60_70,
                           ShotLimitingStatus::REDUCTION_60_70,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
OUSTER_DEPRECATED_CONSTEXP(SHOT_LIMITING_REDUCTION_70_75,
                           ShotLimitingStatus::REDUCTION_70_75,
                           OUSTER_DEPRECATED_LAST_SUPPORTED_0_16);
/// @endcond

}  // namespace core
}  // namespace sdk
}  // namespace ouster
