#pragma once

#include <ouster/lidar_scan.h>
#include <ouster/lidar_scan_set.h>
#include <ouster/types.h>
#include <ouster/visibility.h>

#include <string>
#include <vector>

namespace ouster {
namespace sdk {
namespace mapping {

/**
 * @brief Configuration parameters for the SLAM backend.
 */
struct OUSTER_API_CLASS SlamConfig {
    double min_range = 0.0;    ///< Minimum range of sensor measurements to be
                               ///< considered (meters)
    double max_range = 150.0;  ///< Maximum range of sensor measurements to be
                               ///< considered (meters)
    double voxel_size = 0.0;   ///< Size of the voxel grid for downsampling
    Eigen::Matrix4d initial_pose =
        Eigen::Matrix4d::Identity();     ///< Initial pose of the sensor
    std::string backend = "kiss";        ///< The backend to be used for SLAM
    std::string deskew_method = "auto";  ///< Deskewing method to be applied
};

/**
 * @class SlamBackend
 * @brief Abstract base class for SLAM backend.
 *
 * The SlamBackend class provides an interface for processing LidarScans,
 * estimating poses, and generating point clouds using simultaneous localization
 * and mapping (SLAM) techniques. Implementations of this class are responsible
 * for processing incoming lidar data, retrieving the latest estimated pose,
 * and providing the current point cloud.
 *
 * @note This class is intended to be subclassed; all core methods are pure
 * virtual and must be implemented by derived classes.
 *
 * @see LidarScan
 * @see SlamConfig
 * @see SlamEngine
 */
class OUSTER_API_CLASS SlamBackend {
   public:
    /**
     * @brief Constructs the SlamBackend.
     *
     * @param[in] infos A vector of shared pointers to SensorInfo objects.
     * @param[in] config The SlamConfig object containing configuration
     *                   parameters for the SLAM algorithm.
     */
    OUSTER_API_FUNCTION
    SlamBackend(const std::vector<
                    std::shared_ptr<ouster::sdk::core::SensorInfo>>& infos,
                const SlamConfig& config)
        : infos_(infos), config_(config) {}

    /**
     * @brief SlamBackend destructor.
     */
    OUSTER_API_FUNCTION
    virtual ~SlamBackend() = default;

    /**
     * @brief Let SlamBackend process LidarScans to estimate the new state
     * (pose).
     *
     * This function processes a set of LidarScans provided as vector of shared
     * pointers of LidarScan, The backend returns these LidarScans with their
     * per-column pose corrected.
     *
     * @param[in,out] scans A vector of shared pointers to LidarScan objects to
     * be processed.
     */
    OUSTER_API_FUNCTION
    virtual void update(ouster::sdk::core::LidarScanSet& scans) = 0;

    /**
     * @brief Retrieves the current point cloud from the SLAM backend.
     *
     * This method returns a point cloud representation as a `PointCloudXYZf`
     * object, which contains the latest set of 3D points generated by the SLAM
     * backend.
     *
     * @return A `PointCloudXYZf` object containing the current point cloud
     * data.
     */
    OUSTER_API_FUNCTION
    virtual core::PointCloudXYZf get_point_cloud() const = 0;

   protected:
    std::vector<std::shared_ptr<ouster::sdk::core::SensorInfo>> infos_;
    SlamConfig config_;
};

}  // namespace mapping
}  // namespace sdk
}  // namespace ouster
