#pragma once

#include <ouster/lidar_scan.h>
#include <ouster/lidar_scan_set.h>
#include <ouster/types.h>
#include <ouster/visibility.h>

#include <vector>

#include "slam_backend.h"

namespace ouster {
namespace sdk {
namespace mapping {

/**
 * @class SlamEngine
 * @brief SLAM engine for processing sensor data using specified backend.
 *
 * This class provides an interface for running SLAM (Simultaneous Localization
 * and Mapping) algorithms on lidar and other sensor data.
 *
 * @note Only the "kiss" backend is supported at this time.
 *
 * @see LidarScan
 * @see SlamConfig
 * @see SlamBackend
 */
class OUSTER_API_CLASS SlamEngine {
   public:
    /**
     * @brief Constructs the SlamEngine.
     *
     * @param[in] infos A vector of shared pointers to SensorInfo objects.
     * @param[in] config The SlamConfig object containing configuration
     *                   parameters for the SLAM algorithm.
     *
     * @throws std::runtime_error If the specified backend is not supported.
     */
    OUSTER_API_FUNCTION
    SlamEngine(const std::vector<
                   std::shared_ptr<ouster::sdk::core::SensorInfo>>& infos,
               const SlamConfig& config);

    /**
     * @brief Let SlamEngine process LidarScans to estimate the new state
     * (pose).
     *
     * This function processes a set of LidarScans provided as vector of shared
     * pointers of LidarScan, The engine returns these LidarScans with their
     * per-column pose corrected.
     *
     * @param[in,out] scans A vector of shared pointers to LidarScan objects to
     * be processed.
     */
    OUSTER_API_FUNCTION
    void update(ouster::sdk::core::LidarScanSet& scans);

    /**
     * @brief Retrieves the current point cloud from the SLAM engine.
     *
     * This method returns a point cloud representation as a `PointCloudXYZf`
     * object, which contains the latest set of 3D points generated by the SLAM
     * engine.
     *
     * @return A `PointCloudXYZf` object containing the current point cloud
     * data.
     */
    OUSTER_API_FUNCTION
    ouster::sdk::core::PointCloudXYZf get_point_cloud() const;

   private:
    std::unique_ptr<SlamBackend> backend_;
};

}  // namespace mapping
}  // namespace sdk
}  // namespace ouster
