include "common.fbs";

namespace ouster.sdk.osf.v2;

// Sensor info about a lidar scan
table SensorInfo {
    lidar_sensor_id:uint32; // referenced to metadata.entry[].id with LidarSensor
    scan_stream_id:uint32; // referenced to metadata.entry[].id with LidarScan
    sensor_info:[uint8]; // zstd compressed sensor info json
}

table SensorInfoStream {
    // empty
}


table ClassMapEntry {
    key: uint32;
    value: string;
}

table ClassMap {
    key: string;
    items: [ClassMapEntry];
}

table ClassMapSet {
    items: [ClassMap];
}

union ScanSourceMetadataValue {
    ClassMapSet, Generic: string
}

table ScanSourceMetadataEntry {
    key: string;
    value: ScanSourceMetadataValue;
}

table ScanSourceMetadataSet {
    entries: [ScanSourceMetadataEntry];
}

table ScanSourceMetadataStream {
    // empty
}

// MetadataEntry.type: ouster/v1/os_sensor/SensorInfoStream
root_type SensorInfoStream;
file_identifier "oSIS";
