[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools==69.2.0", "wheel==0.45.1", "flufl.lock", "pip", "nanobind==2.9.2", "numpy", "typing_extensions", "rosbags==0.9.23", "tree_sitter_cpp", "libclang", "tree_sitter"]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
