[metadata]
long_description = file: README.rst
long_description_content_type = text/x-rst
project_urls =
    Ouster SDK Documentation = https://docs.ouster.com/sdk-docs/index.html
    Source Code = https://github.com/ouster-lidar/ouster-sdk
    Changelog = https://docs.ouster.com/sdk-docs/reference/changelog.html
    Migration Guides = https://docs.ouster.com/sdk-docs/migration/migration-0.16.2-1.0.html
    Bug Tracker = https://github.com/ouster-lidar/ouster-sdk/issues
    Ouster Customer Support = https://community.ouster.com/c/software/6
    Ouster-Freeware-EULA =  https://docs.ouster.com/sdk-docs/LICENSE-freeware.txt
classifiers =
    Development Status :: 5 - Production/Stable
    Intended Audience :: Developers
    Intended Audience :: Education
    Intended Audience :: Science/Research
    Operating System :: MacOS
    Operating System :: Microsoft :: Windows
    Operating System :: POSIX
    Operating System :: Unix
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14
    Programming Language :: Python :: Implementation :: CPython
    Topic :: Software Development :: Libraries
    Topic :: System :: Hardware :: Hardware Drivers
    Topic :: Scientific/Engineering
    Topic :: Scientific/Engineering :: Image Processing
    Typing :: Typed
