find_package(PkgConfig QUIET)
if(PKG_CONFIG_FOUND)
  pkg_check_modules(PC_PCAPPLUSPLUS QUIET PcapPlusPlus)
  if(PC_PCAPPLUSPLUS_FOUND)
    set(PCAPPLUSPLUS_VERSION_STRING ${PC_PCAPPLUSPLUS_VERSION})
  endif()
endif()

find_path(PCAPPLUSPLUS_INCLUDE_DIRS
  NAMES PcapPlusPlusVersion.h
  HINTS ${PC_PCAPPLUSPLUS_INCLUDE_DIRS})

find_library(PCAPPLUSPLUS_COMMON_LIBRARY
  NAMES Common++
  HINTS ${PC_PCAPPLUSPLUS_LIBRARY_DIRS})

find_library(PCAPPLUSPLUS_PACKET_LIBRARY
  NAMES Packet++
  HINTS ${PC_PCAPPLUSPLUS_LIBRARY_DIRS})

set(PCAPPLUSPLUS_LIBRARIES
  "${PCAPPLUSPLUS_PACKET_LIBRARY};${PCAPPLUSPLUS_COMMON_LIBRARY}")

if(NOT TARGET pcapplusplus::pcapplusplus)
  add_library(pcapplusplus::pcapplusplus INTERFACE IMPORTED)
  set_target_properties(pcapplusplus::pcapplusplus PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${PCAPPLUSPLUS_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES "${PCAPPLUSPLUS_LIBRARIES}")
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(pcapplusplus
  REQUIRED_VARS
    PCAPPLUSPLUS_LIBRARIES PCAPPLUSPLUS_COMMON_LIBRARY PCAPPLUSPLUS_PACKET_LIBRARY
    PCAPPLUSPLUS_INCLUDE_DIRS
  VERSION_VAR PCAPPLUSPLUS_VERSION_STRING)

mark_as_advanced(
  PCAPPLUSPLUS_INCLUDE_DIRS
  PCAPPLUSPLUS_COMMON_LIBRARY
  PCAPPLUSPLUS_PACKET_LIBRARY)
