#include <nanobind/nanobind.h>
#include <nanobind/ndarray.h>
#include <nanobind/stl/optional.h>  // Ensure standard optional support
#include <nanobind/stl/string.h>
#include <nanobind/stl/vector.h>

#include "common.h"  // NOLINT(unused-includes)

// BEGINNOLINT(misc-use-internal-linkage)
void init_perception(py::module_&, py::module_&);
void init_algorithm(py::module_&, py::module_&);
void init_client(py::module_&, py::module_&);
void init_pcap(py::module_&, py::module_&);
void init_osf(py::module_&, py::module_&);
void init_viz(py::module_&, py::module_&);
void init_mapping(py::module_&, py::module_&);
// ENDNOLINT(misc-use-internal-linkage)

// no lint everything - this macro creates a lot of tidy warnings
// NOLINTNEXTLINE
NB_MODULE(_bindings, module) {
#if defined(SUPPRESS_NANOBIND_LEAK_WARNINGS)
    py::set_leak_warnings(false);
#endif
    module.doc() = R"(
    SDK bindings generated by nanobind.

    This module is generated directly from the C++ code and not meant to be used
    directly.
    )";

    // Nanobind uses module_, not module for the type
    auto client = module.def_submodule("client");
    init_client(client, module);
    auto algorithm = module.def_submodule("algorithm");
    init_algorithm(algorithm, module);
    auto pcap = module.def_submodule("pcap");
    init_pcap(pcap, module);
    auto osf = module.def_submodule("osf");
    init_osf(osf, module);
    auto viz = module.def_submodule("viz");
    init_viz(viz, module);
    auto mapping = module.def_submodule("mapping");
    init_mapping(mapping, module);
    auto perception = module.def_submodule("perception");
    init_perception(perception, module);
}
